Pm 15 tatsat jha neh waiver
DHReSCUnit/dhrescunit.github.io pull request #8
Opened 2024-10-25 19:24 UTC by TatsatJha

I changed the waiver to be in the footer, also updated the .toml file to include that disclaimer

2024-10-25 21:31 UTC, jdamerow requested changes

2024-10-25 21:31 UTC, jdamerow commented on layouts/partials/footer.html
It looks like this file has a slot already planned for the disclaimer text. You just need to uncomment the disclaimerText variable in hugo.toml and then move the printing of the variable to where you currently put the disclaimer directly.

2024-10-28 18:35 UTC, TatsatJha commented
Requested changes should now be added

2024-10-29 13:39 UTC, jdamerow commented
Something is off here:
![image](https://github.com/user-attachments/assets/ee05d7e7-6a76-4736-a580-ea735cc6a7c5)

2024-10-29 13:39 UTC, closed without merging

2024-10-30 19:13 UTC, TatsatJha commented
I see what's going on, I had the webpage on dark mode, I'll have the styling be dynamic instead